- name: prepare needed folder
  file:
    path: "{{item}}"
    state: directory
    owner: root
    group: root
    mode: 0750
  with_items:
    - "/opt/systemd_watcher"

- name: copy cmd
  template:
    src: "templates/service_check"
    dest: "/opt/systemd_watcher/service_check"
    owner: root
    group: root
    mode: 0750

- name: create cron job
  vars:
    name: "Systemd watcher"
    cmd: "/opt/systemd_watcher/service_check"
    file: "ansible_systemd_watcher"
    minute: "*/5"
  import_tasks: roles/cron/tasks/add_cronjob.yml
