- name: set version
  set_fact:
    java_version: '8.252.09.1'
  tags: [ 'update_notifier_config' ]

- name: install archive
  unarchive:
    src: "https://corretto.aws/downloads/resources/{{java_version}}/amazon-corretto-{{java_version}}-linux-x64.tar.gz"
    dest: "/opt"
    remote_src: true
    creates: "/opt/amazon-corretto-{{java_version}}-linux-x64/"
#    creates: "/opt/amazon-corretto-8.212.04.2-linux-x64/"
  register: jdk_exists

# *** ACTIVATE NEW JDK ***
- name: set alternatives => jdk changed
  alternatives:
    name: java
    path: "/opt/amazon-corretto-{{java_version}}-linux-x64//bin/java"
    link: /usr/bin/java
  when: jdk_exists.changed
    
# ***** FINALIZE *****
- name: register update notifier
  vars:
    name: "java"
    type: "github"
    url: "https://github.com/corretto/corretto-8/releases"
    config: { 
      project: "corretto/corretto-8", 
      pattern: "^([0-9\\.\\-]+)$",
      version: "{{java_version}}" 
    }
  import_tasks: roles/update_service/shared/add_software.yml
